### ISSUE TITLE
Failed to restore plugin

### ISSUE THREAD

**Issue by bmi6886** [dpa99c/cordova-plugin-hello-c#1]
Hello, after downloading the test-project and executing "cordova platform add android" I get this Error.

![screenshot 1](https://user-images.githubusercontent.com/34339193/34533436-80a82414-f0ba-11e7-8ab3-6fcc5f31e269.png)

Any idea how to fix this?

thx

**Comment by dpa99c** [comment]
I created the test project for `cordova@6` so it probably needs updating for `cordova@7/8` i.e. needs a `package.json` adding. In the meantime you should be able to add the plugin manually:

    git clone https://github.com/dpa99c/cordova-plugin-hello-c-test && cd cordova-plugin-hello-c-test
    cordova plugin add https://github.com/dpa99c/cordova-plugin-hello-c
    cordova platform add android

**Comment by dpa99c** [comment]
Actually, it might be that cordova now requires the plugin itself to have a `package.json` - will investigate...

**Comment by bmi6886** [comment]
First of all thx for your quick response. I tried it now with cordova 7.0.0 as well as 8.0.0 but it still does not work. I get the same error.

**Comment by dpa99c** [comment]
Yeah, pretty sure the cause is that `cordova@7/8` now requires plugins to have a `package.json` (`cordova@6` did not). I've just added one, so try it again now.

**Comment by bmi6886** [comment]
Nice. It seems to be working. Thx :)
