### ISSUE TITLE
Error initializing Cordova: Class not found

### ISSUE THREAD

**Issue by LucaTrip** [dpa99c/cordova-plugin-hello-c#10]
When I run my Ionic project with this plugin, after the launch on the device appears an alert that says: 

> Error initializing Cordova: Class not found

How can i fix this problem?

**Comment by dpa99c** [comment]
Does this happen if you build and run the [test project](https://github.com/dpa99c/cordova-plugin-hello-c-test) ?

**Comment by LucaTrip** [comment]
No, test project works correctly. I'm integrating the plugin on my ionic project.
My ionic info
```
Ionic:
   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.0, ios 4.5.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, etc

System:
   Android SDK Tools : 26.1.1
   NodeJS            : v9.2.0 
   npm               : 5.5.1
   OS                : Linux 4.15
```

**Comment by dpa99c** [comment]
It must be a problem with your Ionic project then, as opposed to this plugin.
Possibly an incompatibility with one of the ionic plugins e.g. `cordova-plugin-ionic-webview`

You should start with the working test project, then add the plugins you have in your Ionic project one-by-one, building+running each time, to test if one is causing that problem.

**Comment by LucaTrip** [comment]
Okay thank you then I will do like you said. But if i find which plugin is incompatible, how can i go on if that plugin serves me?

**Comment by dpa99c** [comment]
If you find another plugin causes the build to fail you will need to raise an issue against that plugin to fix it:
this plugin is a very simple example of how to use native C libraries in a Cordova project.
As we can see from the example project, this works fine in isolation.
So if another plugin causes it to fail then that plugin needs to be fixed.

**Comment by LucaTrip** [comment]
okay thank you

**Comment by aornano** [comment]
I'm not agree with you. If you launch the latest cordova release with this plugin, it's works very well. So , why you should touch the plugin instead of the current ionic configuration... You risks to damage the working cordova plugin..

**Comment by dpa99c** [comment]
@LucaTrip is the issue above I have raised against `cordova-android` the same as your problem?

**Comment by dpa99c** [comment]
Fixed by https://github.com/dpa99c/cordova-plugin-hello-c/commit/b4ad97e8d44affd17ad4b9cbb4d3ac8ec620620d
