### ISSUE TITLE
iOS 10 is the maximum deployment target for 32-bit targets

### ISSUE THREAD

**Issue by exonent** [dpa99c/cordova-plugin-hello-c#13]
Hi,

I'm getting this error every time I run `./compile-ios`: 
clang: error: invalid iOS deployment version '-miphoneos-version-min=13.5', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

Do you any idea?

**Comment by dpa99c** [comment]
This should be taken care of by PR #12 which is merged to master but not released to npm yet.
Try installing this plugin directly from the master branch.

**Comment by exonent** [comment]
I just comment the iPhoneOS obsolete for me :
```
#buildit armv7 iPhoneOS
#buildit armv7s iPhoneOS
buildit arm64 iPhoneOS
#buildit i386 iPhoneSimulator
buildit x86_64 iPhoneSimulator
```
