### ISSUE TITLE
How can I use structs?

### ISSUE THREAD

**Issue by exonent** [dpa99c/cordova-plugin-hello-c#14]
Hi,

I'm trying to use my C code and works fine, but when I have to call a function that takes Structs as input and/or output, I don't know how to send the information in JS. Example:

### ** .h File **
```
struct input_example {
    struct other_struct othStruct;
    struct internal_struct internalStruct;
    struct stores_external_Struct externalStruct[3];
    char path[200];
    char file [20];
    char database[200];
    int id;
};
struct output_example {
    int id;
    char somechar[100];
    int limitIntegers[15];
    float somefloat;
};
```

### ** .C File **
```
#include "file.h"
long calc_example(struct input_example *input, struct output_example *output)
{
 .... all code ....
}
```

### ** ..js File **
```
/*global cordova, module*/
module.exports = {
    calc_example: function(STRUCT ,successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "HelloCPlugin", "calc_example", [STRUCT]);
    },
```
### How to call a function with input sctructs directly from JS file?
I don't know how to pass parameters as struct values in JS file. May be as an Array, multi-array?

Thank you!

**Comment by dpa99c** [comment]
This example plugin only demonstrates primitive types such as `int` and `string`.
I'm unsure if the Android JNI supports passing of complex types but that is beyond the scope of this simple example.
For iOS it's easier as you only have to map the stringified Javascript structure passed via the Cordova plugin interface to C types in your Objective C plugin implementation.
I'd suggest Googling how to pass complex types using the Android JNI as this is not something I've had need to do so have no experience with.

**Comment by exonent** [comment]
Android is over for this project. iOS is the main.

My problem is when Objective try to read a Struct from JS. 
```

- (void) calc_example:(CDVInvokedUrlCommand *)command
{

    // option 1 - NSString* a = [[command arguments] objectAtIndex:0];
    // option 2 - NSArray* a = [[command arguments] objectAtIndex:0];
    // option 3 - NSDictionary* a = [[command arguments] objectAtIndex:0];
    // More options?

    float output = calc_example(a);
    
    CDVPluginResult* result = [CDVPluginResult
                               resultWithStatus:CDVCommandStatus_OK
                               messageAsDouble:output];

    
    [self.commandDelegate sendPluginResult:result callbackId:command.callbackId];
}


```
