### ISSUE TITLE
Dlib Library

### ISSUE THREAD

**Issue by bmi6886** [dpa99c/cordova-plugin-hello-c#2]
Hello,

do you think it is possible to get the Dlib library working with your code?

thx

**Comment by dpa99c** [comment]
[Dlib](http://dlib.net/) is just one of many C/C++ libraries, and each has its own needs/quirks (e.g. OpenSSL is another that needs specific compilation flags/methodology). Therefore I don't think it's within the scope of this generic example to focus on specific 3rd party libraries.
