### ISSUE TITLE
cordova platform 7.x problems

### ISSUE THREAD

**Issue by LucaTrip** [dpa99c/cordova-plugin-hello-c#7]
hello,
I'm trying to make the test project work (cordova-plugin-hello-c) with cordova@7.1.0 but I get this error:

> cordova run android
cp: copyFileSync: could not write to dest file (code=ENOENT):/home/xxx/workspace/cordova-wrapper-c/platforms/android/res/xml/config.xml

Error: Unhandled error. (Parsing /home/xxx/workspace/cordova-wrapper-c/platforms/android/res/xml/config.xml failed)

I think the problem is that this plugin does not support cordova@7.x. How can I integrate it into my project with cordova@7.x?

**Comment by dpa99c** [comment]
Should now be fixed to work with cordova-android@7 (Android Studio 3) project structure

**Comment by LucaTrip** [comment]
Thank you so much! now works with cordova-android@7!
